### ISSUE TITLE
Error when running ms2pip in the linux terminal

### ISSUE THREAD

**Issue by MarcIsak** [compomics/ms2pip_c#65]
Hi, 

I tried to process a batch of .peprec files in ms2pip (those that Ralf generated for me in issue #61), to create predicted output files in spectronaut.csv format instead of just csv. I noticed that quite a few peprec files, _precursors_split_(00, 03, 04, 07, 08, 09, 11, 16, 17, 18).peprec_, generated the following error when being processed with ms2pip:

_--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/marc/PycharmProjects/MS2PIP/venv/bin/ms2pip", line 8, in <module>
    sys.exit(main())
  File "/home/marc/PycharmProjects/MS2PIP/venv/lib/python3.8/site-packages/ms2pip/__main__.py", line 123, in main
    ms2pip.run()
  File "/home/marc/PycharmProjects/MS2PIP/venv/lib/python3.8/site-packages/ms2pip/ms2pipC.py", line 759, in run
    self._read_peptide_information()
  File "/home/marc/PycharmProjects/MS2PIP/venv/lib/python3.8/site-packages/ms2pip/ms2pipC.py", line 842, in _read_peptide_information
    logger.info(
Message: 'Removed {} unsupported peptide sequences (< 3, > 99     amino acids, or containing B, J, O, U, X or Z).'
Arguments: (11,)_

I think that the message in this error is strange as all peptide sequences are between 7 and 50 AA, and they should not have any of the AAs: B, J, O, U, X or Z. 

Any ideas? The peprec files can be found in issue #61 

Best,

Marc

**Comment by RalfG** [comment]
Hi Marc,
I checked the file with the precursors, and there are in fact peptides with `B`, `Z` and `X` amino acids. There does occur a bug while writing this error message, but that shouldn't influence the results. Does the script continue to run after this error message?
